app:
  name: posted-http-gateway
  version: 0.0.1
  env: ${APP_ENV}

server:
  http:
    addr: 0.0.0.0:8090
    tls:
      enable: true
      server_cert_path: ./certs/server.crt
      server_key_path: ./certs/server.key
  read_timeout: 2s
  write_timeout: 2s
  idle_timeout: 30s

grpc:
  auth_service:
    addr: auth-service:50050
    mtls:
      enable: false
      client_cert_path: ./certs/client.crt
      client_key_path: ./certs/client.key
  posts_service:
    addr: posts-service:50051
    mtls:
      enable: false
      client_cert_path: ./certs/client.crt
      client_key_path: ./certs/client.key