// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: posts/v1/posts.proto

package postspb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	PostedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_posts_v1_posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_posts_v1_posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_posts_v1_posts_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Post) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Posts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posts) Reset() {
	*x = Posts{}
	mi := &file_posts_v1_posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posts) ProtoMessage() {}

func (x *Posts) ProtoReflect() protoreflect.Message {
	mi := &file_posts_v1_posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posts.ProtoReflect.Descriptor instead.
func (*Posts) Descriptor() ([]byte, []int) {
	return file_posts_v1_posts_proto_rawDescGZIP(), []int{1}
}

func (x *Posts) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_posts_v1_posts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_v1_posts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_posts_v1_posts_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type Updates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Updates) Reset() {
	*x = Updates{}
	mi := &file_posts_v1_posts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Updates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Updates) ProtoMessage() {}

func (x *Updates) ProtoReflect() protoreflect.Message {
	mi := &file_posts_v1_posts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Updates.ProtoReflect.Descriptor instead.
func (*Updates) Descriptor() ([]byte, []int) {
	return file_posts_v1_posts_proto_rawDescGZIP(), []int{3}
}

func (x *Updates) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Updates) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Updates       *Updates               `protobuf:"bytes,2,opt,name=updates,proto3" json:"updates,omitempty"`
	UpdateMask    []string               `protobuf:"bytes,3,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_posts_v1_posts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_v1_posts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_posts_v1_posts_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdateRequest) GetUpdates() *Updates {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *UpdateRequest) GetUpdateMask() []string {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_posts_v1_posts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_v1_posts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_posts_v1_posts_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_posts_v1_posts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_v1_posts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_posts_v1_posts_proto_rawDescGZIP(), []int{6}
}

func (x *GetByIDRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsRequest) Reset() {
	*x = GetPostsRequest{}
	mi := &file_posts_v1_posts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsRequest) ProtoMessage() {}

func (x *GetPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_v1_posts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsRequest.ProtoReflect.Descriptor instead.
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return file_posts_v1_posts_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPostsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_posts_v1_posts_proto protoreflect.FileDescriptor

const file_posts_v1_posts_proto_rawDesc = "" +
	"\n" +
	"\x14posts/v1/posts.proto\x12\bposts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a/proto/protovalidate/buf/validate/validate.proto\"\x8c\x02\n" +
	"\x04Post\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\x12&\n" +
	"\bowner_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\aownerId\x12\"\n" +
	"\x05title\x18\x03 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x03\x18@R\x05title\x12!\n" +
	"\x04body\x18\x04 \x01(\tB\r\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x03\x18\x80\x04R\x04body\x127\n" +
	"\tposted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtJ\x04\b\b\x10\x10\"-\n" +
	"\x05Posts\x12$\n" +
	"\x05posts\x18\x01 \x03(\v2\x0e.posts.v1.PostR\x05posts\"V\n" +
	"\rCreateRequest\x12\"\n" +
	"\x05title\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x03\x18@R\x05title\x12!\n" +
	"\x04body\x18\x02 \x01(\tB\r\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x03\x18\x80\x04R\x04body\"P\n" +
	"\aUpdates\x12\"\n" +
	"\x05title\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x03\x18@R\x05title\x12!\n" +
	"\x04body\x18\x02 \x01(\tB\r\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x03\x18\x80\x04R\x04body\"\x98\x01\n" +
	"\rUpdateRequest\x12$\n" +
	"\apost_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06postId\x123\n" +
	"\aupdates\x18\x02 \x01(\v2\x11.posts.v1.UpdatesB\x06\xbaH\x03\xc8\x01\x01R\aupdates\x12,\n" +
	"\vupdate_mask\x18\x03 \x03(\tB\v\xbaH\b\xc8\x01\x01\x92\x01\x02\b\x01R\n" +
	"updateMask\"5\n" +
	"\rDeleteRequest\x12$\n" +
	"\apost_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06postId\"6\n" +
	"\x0eGetByIDRequest\x12$\n" +
	"\apost_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06postId\"G\n" +
	"\x0fGetPostsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12 \n" +
	"\x05limit\x18\x02 \x01(\rB\n" +
	"\xbaH\a\xc8\x01\x01*\x02\x18dR\x05limit2\xa0\x02\n" +
	"\fPostsService\x121\n" +
	"\x06Create\x12\x17.posts.v1.CreateRequest\x1a\x0e.posts.v1.Post\x121\n" +
	"\x06Update\x12\x17.posts.v1.UpdateRequest\x1a\x0e.posts.v1.Post\x129\n" +
	"\x06Delete\x12\x17.posts.v1.DeleteRequest\x1a\x16.google.protobuf.Empty\x123\n" +
	"\aGetByID\x12\x18.posts.v1.GetByIDRequest\x1a\x0e.posts.v1.Post\x12:\n" +
	"\fGetSelfPosts\x12\x19.posts.v1.GetPostsRequest\x1a\x0f.posts.v1.PostsB.Z,github.com/chishkin-afk/posted/posts;postspbb\x06proto3"

var (
	file_posts_v1_posts_proto_rawDescOnce sync.Once
	file_posts_v1_posts_proto_rawDescData []byte
)

func file_posts_v1_posts_proto_rawDescGZIP() []byte {
	file_posts_v1_posts_proto_rawDescOnce.Do(func() {
		file_posts_v1_posts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_posts_v1_posts_proto_rawDesc), len(file_posts_v1_posts_proto_rawDesc)))
	})
	return file_posts_v1_posts_proto_rawDescData
}

var file_posts_v1_posts_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_posts_v1_posts_proto_goTypes = []any{
	(*Post)(nil),                  // 0: posts.v1.Post
	(*Posts)(nil),                 // 1: posts.v1.Posts
	(*CreateRequest)(nil),         // 2: posts.v1.CreateRequest
	(*Updates)(nil),               // 3: posts.v1.Updates
	(*UpdateRequest)(nil),         // 4: posts.v1.UpdateRequest
	(*DeleteRequest)(nil),         // 5: posts.v1.DeleteRequest
	(*GetByIDRequest)(nil),        // 6: posts.v1.GetByIDRequest
	(*GetPostsRequest)(nil),       // 7: posts.v1.GetPostsRequest
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_posts_v1_posts_proto_depIdxs = []int32{
	8, // 0: posts.v1.Post.posted_at:type_name -> google.protobuf.Timestamp
	8, // 1: posts.v1.Post.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: posts.v1.Posts.posts:type_name -> posts.v1.Post
	3, // 3: posts.v1.UpdateRequest.updates:type_name -> posts.v1.Updates
	2, // 4: posts.v1.PostsService.Create:input_type -> posts.v1.CreateRequest
	4, // 5: posts.v1.PostsService.Update:input_type -> posts.v1.UpdateRequest
	5, // 6: posts.v1.PostsService.Delete:input_type -> posts.v1.DeleteRequest
	6, // 7: posts.v1.PostsService.GetByID:input_type -> posts.v1.GetByIDRequest
	7, // 8: posts.v1.PostsService.GetSelfPosts:input_type -> posts.v1.GetPostsRequest
	0, // 9: posts.v1.PostsService.Create:output_type -> posts.v1.Post
	0, // 10: posts.v1.PostsService.Update:output_type -> posts.v1.Post
	9, // 11: posts.v1.PostsService.Delete:output_type -> google.protobuf.Empty
	0, // 12: posts.v1.PostsService.GetByID:output_type -> posts.v1.Post
	1, // 13: posts.v1.PostsService.GetSelfPosts:output_type -> posts.v1.Posts
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_posts_v1_posts_proto_init() }
func file_posts_v1_posts_proto_init() {
	if File_posts_v1_posts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_posts_v1_posts_proto_rawDesc), len(file_posts_v1_posts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_posts_v1_posts_proto_goTypes,
		DependencyIndexes: file_posts_v1_posts_proto_depIdxs,
		MessageInfos:      file_posts_v1_posts_proto_msgTypes,
	}.Build()
	File_posts_v1_posts_proto = out.File
	file_posts_v1_posts_proto_goTypes = nil
	file_posts_v1_posts_proto_depIdxs = nil
}
